# Generated by Django 3.2.6 on 2021-08-28 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='end_at',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='run',
            name='start_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
